apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-bazarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: lscr.io/linuxserver/bazarr:latest
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
        ports:
        - containerPort: 6767
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: media-volume
          mountPath: /movies
        - name: media-volume
          mountPath: /tv-shows
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-bazarr
      - name: media-volume
        persistentVolumeClaim:
          claimName: media