apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-torrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: WEBUI_PORT
          value: "8080"
        - name: TORRENTING_PORT
          value: "6881"
        volumeMounts:
        - name: torrent-media
          mountPath: /downloads
        - name: config-volume
          mountPath: /config
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 6881
          protocol: TCP
        - containerPort: 6881
          protocol: UDP
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-torrent
      - name: torrent-media
        persistentVolumeClaim:
          claimName: media